create schema nw201801;
CREATE USER 'nwuser'@'localhost' IDENTIFIED WITH mysql_native_password;
GRANT ALL PRIVILEGES ON nw201801.* TO 'nwuser'@'localhost' REQUIRE NONE WITH GRANT OPTION MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
SET PASSWORD FOR 'nwuser'@'localhost' = 'nwuser.2018';
